services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
      args:
        # if changing the port, also change it in the nginx.conf
        PORT: 5000
    env_file:
      - backend/.env
    environment:
      FLASK_APP: application.py
      DEBUG: false
      ENV: production
    volumes:
      - ./log/backend:/app/log

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
      args:
        NEXT_PUBLIC_GPUSER_API_URL: http://localhost:${GPUSER_PORT:?err}/api
    depends_on:
      - backend
  
  nginx:
    image: nginx:latest
    ports:
      - "${GPUSER_PORT:?err}:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend
