version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
      args:
        PORT: 5000
    env_file:
      - backend/.env
    environment:
      FLASK_APP: application.py
      DEBUG: false
      ENV: production

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
      args:
        NEXT_PUBLIC_GPUSER_API_URL: http://localhost:${GPUSER_PORT:?err}/api
    depends_on:
      - backend
  
  nginx:
    image: nginx:latest
    ports:
      - "${GPUSER_PORT:?err}:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend
