FROM node:18-alpine AS build
ARG NEXT_PUBLIC_GPUSER_API_URL=http://localhost:5000
ENV NEXT_PUBLIC_GPUSER_API_URL=${NEXT_PUBLIC_GPUSER_API_URL}
WORKDIR /app
COPY frontend/package*.json ./
RUN npm ci
COPY ./frontend .
RUN npm run build

FROM node:18-alpine AS runtime
WORKDIR /app
COPY frontend/package*.json ./
RUN npm ci --omit=dev
COPY --from=build /app/.next ./.next
COPY --from=build /app/public ./public

EXPOSE 3000
USER node
CMD ["npm", "start"]
