FROM python:3.12-bookworm

ARG PORT=5000
ENV PORT=$PORT

COPY ./backend /app
WORKDIR /app

RUN pip install -r requirements.txt --no-cache-dir

EXPOSE $PORT
CMD gunicorn application:app -b 0.0.0.0:$PORT
