services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
      args:
        - USER_UID=${USER_UID:?err}
        - USER_GID=${USER_GID:?err}
    volumes:
      - ..:/workspace:cached
    command: sleep infinity
    links:
      - frontend
    environment:
      FLASK_APP: application.py
      DEBUG: true
      ENV: development

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
      args:
        - USER_UID=${USER_UID:?err}
        - USER_GID=${USER_GID:?err}
    volumes:
      - ..:/workspace:cached
    command: sleep infinity
